apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  password: "Hello890!"
  host: "cw-event-db.cpua0oyyqtqw.eu-west-1.rds.amazonaws.com"
  port: "5432"
  dbname: "postgres"
  username: "cwadmin"
